\pset footer off
SET client_min_messages TO WARNING;
\set ON_ERROR_STOP ON
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ABW','Aruba','AW');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('AFG','Afghanistan','AF');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('AGO','Angola','AO');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('AIA','Anguilla','AI');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ALA','Åland Islands','AX');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ALB','Albania','AL');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('AND','Andorra','AD');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ANT','Netherlands Antilles','AN');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ARE','United Arab Emirates (the)','AE');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ARG','Argentina','AR');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ARM','Armenia','AM');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ASM','American Samoa','AS');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ATA','Antarctica','AQ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ATF','French Southern Territories (the)','TF');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ATG','Antigua and Barbuda','AG');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('AUS','Australia','AU');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('AUT','Austria','AT');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('AZE','Azerbaijan','AZ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BDI','Burundi','BI');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BEL','Belgium','BE');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BEN','Benin','BJ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BES','Bonaire, Sint Eustatius and Saba','BQ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BFA','Burkina Faso','BF');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BGD','Bangladesh','BD');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BGR','Bulgaria','BG');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BHR','Bahrain','BH');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BHS','Bahamas (the)','BS');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BIH','Bosnia and Herzegovina','BA');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BLM','Saint Barthelemy','BL');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BLR','Belarus','BY');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BLZ','Belize','BZ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BMU','Bermuda','BM');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BOL','Bolivia (Plurinational State of)','BO');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BRA','Brazil','BR');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BRB','Barbados','BB');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BRD','Barbados','BB');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BRN','Brunei Darussalam','BN');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BTN','Bhutan','BT');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BVT','Bouvet Island','BV');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('BWA','Botswana','BW');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('CAF','Central African Republic (the)','CF');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('CAN','Canada','CA');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('CCK','Cocos (Keeling) Islands (the)','CC');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('CHE','Switzerland','CH');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('CHL','Chile','CL');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('CHN','China','CN');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('CIV','Côte d Ivoire','CI');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('CMR','Cameroon','CM');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('COD','Congo (the Democratic Republic of the)','CD');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('COG','Congo (the)','CG');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('COK','Cook Islands (the)','CK');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('COL','Colombia','CO');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('COM','Comoros (the)','KM');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('CPV','Cabo Verde','CV');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('CRI','Costa Rica','CR');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('CUB','Cuba','CU');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('CUW','Curaçao','CW');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('CXR','Christmas Island','CX');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('CYM','Cayman Islands (the)','KY');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('CYP','Cyprus','CY');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('CZE','Czechia','CZ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('DEU','Germany','DE');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('DJI','Djibouti','DJ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('DMA','Dominica','DM');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('DNK','Denmark','DK');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('DOM','Dominican Republic (the)','DO');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('DZA','Algeria','DZ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ECU','Ecuador','EC');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('EGY','Egypt','EG');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ERI','Eritrea','ER');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ESH','Western Sahara','EH');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ESP','Spain','ES');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('EST','Estonia','EE');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ETH','Ethiopia','ET');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('FIN','Finland','FI');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('FJI','Fiji','FJ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('FLK','Falkland Islands (the) [Malvinas]','FK');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('FRA','France','FR');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('FRO','Faroe Islands (the)','FO');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('FSM','Micronesia (Federated States of)','FM');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('GAB','Gabon','GA');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('GBR','United Kingdom of Great Britain and Northern Ireland (the)','GB');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('GEO','Georgia','GE');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('GGY','Guernsey','GG');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('GHA','Ghana','GH');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('GIB','Gibraltar','GI');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('GIN','Guinea','GN');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('GLP','Guadeloupe','GP');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('GMB','Gambia (the)','GM');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('GNB','Guinea-Bissau','GW');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('GNQ','Equatorial Guinea','GQ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('GRC','Greece','GR');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('GRD','Grenada','GD');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('GRL','Greenland','GL');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('GTM','Guatemala','GT');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('GUF','French Guiana','GF');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('GUM','Guam','GU');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('GUY','Guyana','GY');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('HKG','Hong Kong','HK');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('HMD','Heard Island and McDonald Islands','HM');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('HND','Honduras','HN');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('HRV','Croatia','HR');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('HTI','Haiti','HT');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('HUN','Hungary','HU');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('IDN','Indonesia','ID');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('IMN','Isle of Man','IM');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('IMY','Isle Of Man','IM');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('IND','India','IN');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('IOT','British Indian Ocean Territory (the)','IO');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('IRL','Ireland','IE');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('IRN','Iran (Islamic Republic of)','IR');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('IRQ','Iraq','IQ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ISL','Iceland','IS');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ISR','Israel','IL');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ITA','Italy','IT');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('JAM','Jamaica','JM');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('JEY','Jersey','JE');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('JOR','Jordan','JO');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('JPN','Japan','JP');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('KAZ','Kazakhstan','KZ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('KEN','Kenya','KE');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('KGZ','Kyrgyzstan','KG');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('KHM','Cambodia','KH');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('KIR','Kiribati','KI');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('KNA','Saint Kitts and Nevis','KN');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('KOR','Korea (the Republic of)','KR');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('KWT','Kuwait','KW');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('LAO','Lao People s Democratic Republic (the)','LA');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('LBN','Lebanon','LB');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('LBR','Liberia','LR');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('LBY','Libya','LY');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('LCA','Saint Lucia','LC');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('LIE','Liechtenstein','LI');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('LKA','Sri Lanka','LK');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('LSO','Lesotho','LS');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('LTU','Lithuania','LT');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('LUX','Luxembourg','LU');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('LVA','Latvia','LV');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MAC','Macao','MO');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MAF','Saint Martin (French part)','MF');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MAR','Morocco','MA');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MCO','Monaco','MC');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MDA','Moldova (the Republic of)','MD');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MDG','Madagascar','MG');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MDV','Maldives','MV');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MEX','Mexico','MX');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MHL','Marshall Islands (the)','MH');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MKD','Republic of North Macedonia','MK');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MLI','Mali','ML');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MLT','Malta','MT');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MMR','Myanmar','MM');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MNE','Montenegro','ME');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MNG','Mongolia','MN');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MNP','Northern Mariana Islands (the)','MP');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MOZ','Mozambique','MZ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MRT','Mauritania','MR');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MSR','Montserrat','MS');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MTQ','Martinique','MQ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MUS','Mauritius','MU');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MWI','Malawi','MW');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MYS','Malaysia','MY');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('MYT','Mayotte','YT');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('NAM','Namibia','NA');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('NCL','New Caledonia','NC');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('NER','Niger (the)','NE');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('NFK','Norfolk Island','NF');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('NGA','Nigeria','NG');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('NIC','Nicaragua','NI');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('NIU','Niue','NU');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('NLD','Netherlands (the)','NL');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('NOR','Norway','NO');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('NPL','Nepal','NP');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('NRU','Nauru','NR');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('NZL','New Zealand','NZ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('OMN','Oman','OM');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('PAK','Pakistan','PK');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('PAN','Panama','PA');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('PCN','Pitcairn','PN');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('PER','Peru','PE');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('PHL','Philippines (the)','PH');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('PLW','Palau','PW');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('PNG','Papua New Guinea','PG');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('POL','Poland','PL');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('PRI','Puerto Rico','PR');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('PRK','Korea (the Democratic People s Republic of)','KP');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('PRT','Portugal','PT');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('PRY','Paraguay','PY');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('PSE','Palestine, State of','PS');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('PYF','French Polynesia','PF');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('QAT','Qatar','QA');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('REU','Reunion','RE');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ROU','Romania','RO');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('RUS','Russian Federation (the)','RU');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('RWA','Rwanda','RW');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SAU','Saudi Arabia','SA');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SDN','Sudan (the)','SD');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SEN','Senegal','SN');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SGP','Singapore','SG');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SGS','South Georgia and the South Sandwich Islands','GS');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SHN','Saint Helena, Ascension and Tristan da Cunha','SH');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SJM','Svalbard and Jan Mayen','SJ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SLB','Solomon Islands','SB');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SLE','Sierra Leone','SL');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SLV','El Salvador','SV');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SMR','San Marino','SM');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SOM','Somalia','SO');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SPM','Saint Pierre and Miquelon','PM');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SRB','Serbia','RS');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SSD','South Sudan','SS');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('STP','Sao Tome and Principe','ST');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SUR','Suriname','SR');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SVK','Slovakia','SK');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SVN','Slovenia','SI');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SWE','Sweden','SE');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SWZ','Eswatini','SZ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SXM','Sint Maarten (Dutch part)','SX');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SYC','Seychelles','SC');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('SYR','Syrian Arab Republic','SY');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('TCA','Turks and Caicos Islands (the)','TC');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('TCD','Chad','TD');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('TGO','Togo','TG');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('THA','Thailand','TH');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('TJK','Tajikistan','TJ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('TKL','Tokelau','TK');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('TKM','Turkmenistan','TM');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('TLS','Timor-Leste','TL');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('TON','Tonga','TO');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('TTO','Trinidad and Tobago','TT');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('TUN','Tunisia','TN');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('TUR','Turkey','TR');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('TUV','Tuvalu','TV');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('TWN','Taiwan (Province of China)','TW');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('TZA','Tanzania, United Republic of','TZ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('UGA','Uganda','UG');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('UKR','Ukraine','UA');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('UMI','United States Minor Outlying Islands (the)','UM');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('URY','Uruguay','UY');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('USA','United States of America (the)','US');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('UZB','Uzbekistan','UZ');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('VAT','Holy See (the)','VA');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('VCT','Saint Vincent and the Grenadines','VC');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('VEN','Venezuela (Bolivarian Republic of)','VE');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('VGB','Virgin Islands (British)','VG');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('VIR','Virgin Islands (U.S.)','VI');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('VNM','Viet Nam','VN');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('VUT','Vanuatu','VU');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('WLF','Wallis and Futuna','WF');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('WSM','Samoa','WS');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('YEM','Yemen','YE');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ZAF','South Africa','ZA');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ZMB','Zambia','ZM');
INSERT INTO public.paises (abreviatura_pais,nombre,alfa_dos) VALUES('ZWE','Zimbabwe','ZW');


