\pset footer off
SET client_min_messages TO WARNING;
\set ON_ERROR_STOP ON

INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('835.001.707-2 ','SCS ADUANERA INC');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('800.246.993-7 ','SEAPORT S.A.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('860.532.426-7 ','NAVES S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('802.008.802-6 ','NAVENAL S.A.S ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.477.097-6 ','DEEP BLUE SHIP AGENCY SAS ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('830.506.584-3 ','MULTIPORT E.U.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('806.004.569-0 ','AGENCIA OCEANICA S.A.S. OCEANIC');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('860.031.615-2 ','AGUNSA COLOMBIA S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('800.116.249-8 ','AGENCIA MARITIMA TRANSMARES S.A.S');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('800.249.687-1 ','MEDITERRANEAN SHIPPING COMPANY COLOMBIA S.A.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('860.005.101-9 ','GERLEINCO S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.189.529-0 ','AGENCIA MARITIMA AGUILAR E.U.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('890.903.069-2 ','ROLDAN Y COMPAAAA S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('835.001.500-5 ','BMA PACIFICO S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('31.377.890-1','CIELO MARES ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('811.001.005-3 ','GLOBAL SHIPPING AGENCIES S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.374.883-6 ','JANS MAR COLOMBIA S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('800.067.129-1 ','LBH COLOMBIA S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('860.006.765-3 ','CIA. TRANSPORTADORA S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('800.159.356-2 ','FRONTIER AGENCIA MARITIMA S.A.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.469.304-2 ','OCEANTRUST SHIP AGENCY S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('830.113.435-7 ','BROOM COLOMBIA S.A. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.260.012-8 ','INTERNATIONAL MARITIME AGENCY S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('16483412','BELALCAZAR MONTAAO ALEXANDER ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('800.134.133-9 ','NAVES Y SERVICIOS S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('890.916.161-9 ','AGENCIA MARITIMA TURBADUANA SOCIEDAD POR ACCIONES SIMPLIFICADA ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('39300088','LONDOAO LAPEZ MARAA INAS');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('31.952.153-6','ALVAREZ PALACIO BLANCA MARAA');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('12.905.045-1','BENAVIDES ESTUPIAAN BOLIVAR SILVIO ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.411.544-3 ','LINDA MAR SAS ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('835.000.630-1 ','MARSERV LTDA');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('16.468.714-8','GARCES CEBALLOS SEGUNDO GUILLERMO ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('12907381','BALVINO GUTIARREZ MARTANEZ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('12.904.400-7','PADILLA CASTRO CLEMENTE ALIRIO');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('2.935.836-5 ','MARIANA BRAVO DE MEJIA');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('840.000.591-9 ','SERVIPAC E.U. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('802.019.981-3 ','SCS ADUANERA INC. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.088.812-7 ','CARIBBEAN AMERICAN SHIPPING AGENCY S.A.S');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('800.182.535-0 ','CARIBBEAN WORLD WIDE SHIPPING SERVICES AGENCYS.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.824.728-4 ','GRUPO AGENCIA & LOGISTICA S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.897.369-6 ','SERVIMAR DE COLOMBIA S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('800.235.053-1 ','MAERSK COLOMBIA S.A.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.290.842-2 ','MARINAS DE COLOMBIA S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('802.010.775-1 ','BULK MARITIME AGENCIES S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.590.941-0 ','7 SEAS ENERGY S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('901.102.112-3 ','PHARO SHIP AGENT S.A.S');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('806.013.504-0 ','ATLAS SHIPPING SERVICES S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('800.250.763-5 ','SEABOARD DE COLOMBIA S.A. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('800.220.366-6 ','FRONTIER AGENCIA MARITIMA DEL CARIBE S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('806.004.303-9 ','INTERSHIP AGENCY S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('860.077.997-9 ','SERVIESTIBA LTDA. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('800.256.551-8 ','ISACOL S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('800.113.951-7 ','MARADUANA S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.587.386-1 ','MERIDIAN NAVIGATION S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.864.362-3 ','VINODOL COLOMBIA S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.261.482-0 ','SERVICIOS NAVIEROS COLOMBIANOS S.A. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.180.400-9 ','TANK OIL SHIPPING S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.282.820-7 ','COLOMBIAN SHIPPING AGENCY S.A.S.-COLSHIPPING');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('901.122.463-9 ','SEVEN ELEPHANTS S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('806.000.321-3 ','N Y N SHIPPING S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.606.944-4 ','ROLCO SHIPPING S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.624.883-1 ','T. PARKER HOST COLOMBIA S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('830.511.560-7 ','AGENCIA MARITIMA Y DE EMPLEO ECLIPSE LTDA. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('800.195.272-5 ','MARITIMA INTERAMERICANA DE NAVES S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('890.115.984-6 ','COLVAPORES S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.509.692-8 ','REMAR AGENCY S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('901.205.751-2 ','SCS ADUANERA COLOMBIA S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('860.001.560-8 ','NAVEMAR S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('901.087.342-6 ','AGENCIA MARITIMA MAR PACAFICOS S.A.S');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('800.181.561-8 ','AGENCIA MARITIMA ALTAMAR LTDA. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.149.893-6 ','OCEANS MARITIME AGENCY COLOMBIA S.A.S ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.330.976-3 ','COLMARITIME SAS ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.473.090-7 ','CRUISING SERVICE MARINE AGENCY S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('806.013.086-3 ','WHITE LIGHT AGENCY LTDA ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.342.455-1 ','ALASMAR LIMITADA');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.177.167-6 ','ALPEMAR S.A.S. AGENTES MARATIMOS.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('806.009.758-9 ','IMEX EXPRESS SERVICE S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('806.007.093-0 ','BRISAS DEL MAR LTDA ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('800.194.221-5 ','ROZO Y CIA. S.A.S. AGENTES MARITIMOS');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('830.146.163-0 ','WILHELMSEN SHIPS SERVICE COLOMBIA S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.014.813-7 ','SCS ADUANERA INC.-SUCURSAL COVEAAS ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('92.535.425-8','CAMPO GARAY GONZALO ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.035.520-4 ','COFAUMARU LTDA');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('890.404.744-5 ','SERVINAVES LTDA ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('806.000.103-4 ','CARIBBEAN SHIPPING AGENCY SERVICIOS MARATIMOS DEL CARIBE S.A.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.260.086-2 ','COLOMBIAN FISHERIES S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.368.565-4 ','CARTAGENA CARIBBEAN MARINE AGENCY LTDA. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('802.017.871-2 ','BMA ATLANTICO S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.243.764-6 ','CSAV GROUP AGENCY COLOMBIA LTDA.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('806.012.551-2 ','SCS ADUANERA INC.-SUCURSAL CARTAGENA');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('890.107.200-7 ','AGENCIA MARITIMA INTERNACIONAL S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('806.016.268-0 ','ASERCOL MARITIMA S.A.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.373.456-1 ','SEA TRANSPORT LIMITADA');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('830.035.850-6 ','AGENTES PORTUARIOS S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('73072533','BUSH HOWARD BERNARDO BASILIO');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('18.002.138-2','LEVER HUDGSON ELVIS IVAN');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('18009963','AGENCIA MARITIMA K.J.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.504.340-8 ','SEA SPORT SHIPPING AGENCY S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('9085696','AGENCIA MARITIMA SERRANA ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('15242762','AGENCIA MARITIMA J.F. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('800.085.420-7 ','CARLOS RAMOS TORREGLOSA & COMPAAAA LTDA ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('827.000.681-6 ','CAUSIL ROJAS Y CIA S. EN C.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('827.000.202-1 ','HOWARD Y CIA S EN C ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('4092211','CASTELLANOS CASTILLO HACTOR DARAO ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.087.622-1 ','AGENCIA MARITIMA COLOMBIAN SEAS S.A.S. - ACOLSEAS');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('10.385.135-4','CIFUENTES QUIAONES ANTONIO EDUARDO ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('891.701.623-1 ','VICTOR ABELLO Y ASOCIADOS LTDA');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('17192576','ARENAS MCLAUGHLIN LUIS HUMBERTO ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('15.242.762-7','FUENTES PEREZ JORGE LUIS');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.141.249-6 ','AGENPORT LTDA ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.025.233-2 ','INVERSIONES MARINA TURASTICA S.A.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.371.443-5 ','CARIBBEAN SEA OF COLOMBIA-SHIPPING AGENCY S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('819.005.800-1 ','SCS ADUANERA INC. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.629.627-3 ','MAR Y SOL SHIPPING S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.105.050-5 ','AGENCIA MARITIMA FULLNAVES S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('839.000.441-9 ','PARAJIMARU LIMITADA ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.502.353-4 ','HOST COLOMBIA S.A.S ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.786.714-8 ','OCEAN & RIVER SHIPPING AGENCY S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('835.001.843-6 ','SEAWAY LTDA.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('901.029.341-1 ','ING MAR AGENCIA MARITIMA INTERNACIONAL SAS ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.657.493-2 ','DELIVERANCE SHIPPING LINE S.A.S ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('3564985-0 ','ECHAVARRIA MUAOZ GABRIEL ANGEL ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('1.017.195.497-6 ','AGENCIA MARITIMA CONTINENTAL');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900621981-1 ','INVERSIONES ONE PIECE SAS ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('800.192.024-1 ','AQUARIUS SHIPPING COLOMBIA LTDA.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('806.004.474-1 ','LOGASTICA MARITIMA INTEGRAL S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('66746924','ARROYO TRIVIAO MARIA YASMIN');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('capitaniapuerto ','CAPITANIA PUERTO');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('85.471.900-3','GESTIAN MARITIMA');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('800.255.873-1 ','ORCASITAS & GOMEZ LIMITADA');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.544.274-0 ','SMART SHIPPING SAS');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.735.620-6 ','AGENCIA MARITIMA DELTA SHIPPING S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('860.014.570-8 ','COMPAAIA DE TURISMO BARA LTDA.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('123456789','NO APLICA ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.609.868-6 ','AGENTES MARATIMOS ESPECIALIZADOS S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.491.287-7 ','LAUCAM MARITIMA S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.760.555-0 ','ORION MARITIME SERVICES S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.298.043-0 ','HAPAG LLOYD COLOMBIA LTDA.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.863.379-3 ','EMPRESA COLOMBIANA DE SERVICIOS MARITIMOS S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.667.175-8 ','COLBARCOS S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('901.070.980-0 ','GLOBAL MARINE LINDA S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.863.207-5 ','SEABOW SHIPPING S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.462.019-6 ','DELFIN EXPRESS AGENCY S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('901.293.952-1 ','GUAJIRA TRADING GROUP S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.600.609-4 ','3 OCEANS S.A.S. ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('901.312.082-1 ','AGENCIA MARITIMA MACUIRA MAR S.A.S');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.468.825-3 ','MAXORATA SHIPPING INTERNATIONAL COMPANY S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('901.190.594-5 ','NEWBALL OCEAN GMG S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('901.183.474-0 ','OCEAN BLUE AGENCY S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('901.146.041-8 ','INTERNATIONAL MARITIME AND FISHERIES AGENCY S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('901.304.043-0 ','ANCLAR SOLUCIONES SAS - ZOMAC ');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('900.967.795-1 ','MALPELO SHIP AGENCY S.A.S.');
INSERT INTO simar.agencianave (id_agencia_arribo, agencia_arribo) VALUES('901.212.191-7 ','CARTAGENA SEA AGENCY & BROKERAGE S.A.S. ');



