\pset footer off
SET client_min_messages TO WARNING;
\set ON_ERROR_STOP ON
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(1,'PASAJE ',1,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(110,'TRANSPORTADOR PASAJEROS (CRUCERO)',2,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(111,'TRANSPORTE DE CARGA Y PASAJEROS',1,0);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(119,'CARGA GENERAL',1,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(120,'CARGA REFRIGERADA',3,2);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(121,'BARCAZA TRANSPORTE GRANEL LIQUIDO',2,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(129,'REFRIGERADOR CC',3,2);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(130,'TRANSPORTADOR DE CONTAINERS',3,2);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(143,'SEMI SUMERGIBLE - TRANSPORTE CARGA SOBREDIMENSIONADA',3,3);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(145,'RO/RO',2,2);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(146,'RO/RO C.C',4,2);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(171,'TRANSPORTADOR VEHICULOS',4,2);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(180,'TRANSPORTADOR DE GANADO',3,3);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(200,'TANQUEROS',3,3);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(221,'TANQUERO QUIMICOS',2,2);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(222,'TANQUERO ACEITES COMESTIBLES',3,2);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(3,'CARGA',1,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(300,'TRANSPORTE PASAJEROS RO/RO',3,2);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(330,'FERRY',2,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(4,'TANQUEROS',2,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(400,'GRANELERO / CARGO CONTAINER',3,0);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(401,'GRANELERO POR VOLUMEN',3,2);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(402,'GRANELERO AUTO DESCARGABLE',3,2);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(450,'GRANELERO / ACEITE',4,3);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(5,'LPG',3,2);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(510,'PESQUERO',2,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(516,'VELERO',1,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(517,'CONTROL DE POLUCION',2,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(518,'CATAMARAN',1,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(521,'FACTORIA PESCADO',1,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(534,'TRANSPORTADOR PESCADO',1,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(553,'BALLENERO',1,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(6,'PESCA',1,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(613,'TRANSPORTADOR MINERAL ',3,3);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(643,'DRAGA - NO ESPECIFICA ',2,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(644,'PLATAFORMA EXPLORACION ',3,2);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(645,'SUMINISTRO INSTALACIONES ',2,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(646,'SERVICIO EN PUERTO ',2,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(647,'TRANSPORTE DE PASAJEROS ',1,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(648,'LANCHAS DE DESEMBARCO ',1,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(650,'MULTIPONTON ',3,2);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(660,'GRUA FLOTANTE ',2,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(7,'REMOLCADORES ',2,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(710,'INVESTIGACION ',2,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(711,'INSTALACION DE FIBRA ',3,2);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(8,'RECREO O DEPORTIVOS ',1,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(810,'YATE ',2,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(830,'APOYO LOGISTICO ALTAMAR ',1,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(9,'TRANSPORTADOR CEMENTO ',2,2);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(903,'REMOLCADOR -TUG- ',1,1);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(905,'TANQUERO TRANSPORTE ASFALTO ',2,2);
INSERT INTO public.tiponave (cod_tiponave, nom_tiponave, categoria_trb, categoria_eslora) VALUES(99,'OTRO',1,1);
