INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('ABW','Aruba ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('AFG','Afganistan');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('AGO','Angola');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('AIA','Anguilla');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('ALB','Albania ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('AND','Andorra ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('ANT','Netherlands Antilles');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('ARE','United Arab Emirates');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('ARG','Argentina ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('ASM','American Samoa');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('ATG','Antigua And Barbuda ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('AUS','Australia ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('AUT','Austria ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('BEL','Belgium ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('BEN','Benin ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('BGD','Bangladesh');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('BGR','Bulgaria');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('BHR','Bahrain ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('BHS','Bahamas ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('BLZ','Belize');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('BMU','Bermuda ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('BOL','Bolivia ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('BRA','Brazil');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('BRB','Barbados');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('BRD','Barbados');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('BRN','Brunei Darussalam ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('CAN','Canada');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('CCK','Cook, Islas ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('CHE','Switzerland ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('CHL','Chile ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('CHN','China ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('CIV','Cote D Ivoire ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('CMR','Equatorial Guinea ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('COD','Democratic Republic Of The Congo');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('COG','Congo ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('COL','Colombia');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('COM','Comoros ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('CPV','Cape Verde');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('CRI','Costa Rica');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('CUB','Cuba');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('CUW','Curacao ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('CYM','Cayman Islands');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('CYP','Cyprus');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('CZE','Checoslovaquia');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('DEU','Germany ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('DJI','Djibouti');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('DMA','Dominica');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('DNK','Denmark ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('DOM','Dominican Republic');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('DZA','Algeria ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('ECU','Ecuador ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('EGY','Egypt ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('ESH','Western Sahara');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('ESP','Spain ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('EST','Estonia ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('FIN','Finland ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('FJI','Fiji');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('FLK','Falkland Islands (Malvinas) ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('FRA','France');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('FRO','Faroe Islands ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('FSM','Estados Federados Micronesia');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('GAB','Gabon ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('GBR','U.K. Of Great Britain And Northern Ireland');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('GEO','Georgia ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('GHA','Ghana ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('GIB','Gibraltar ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('GIN','Guinea');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('GLP','Guadeloupe');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('GMB','Gambia');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('GNB','Guinea-Bissau ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('GNQ','Equatorial Guinea ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('GRC','Greece');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('GRD','Grenada ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('GTM','Guatemala ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('GUF','French Guiana ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('GUM','Guam');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('GUY','Guyana');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('HKG','Hong Kong ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('HND','Honduras');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('HRV','Croatia ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('HTI','Dominican Republic');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('HUN','Hungria ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('IDN','Indonesia ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('IMN','Isla De Man ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('IMY','Isle Of Man ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('IND','India ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('IRL','Ireland ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('IRN','Iran(Islamic Republic Of) ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('IRQ','Iraq');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('ISL','Iceland ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('ISR','Israel');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('ITA','Italy ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('JAM','Jamaica ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('JEY','Jersey');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('JPN','Japan ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('KEN','Kenya ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('KHM','Cambodia');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('KIR','Kiribati');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('KNA','Saint Kitts And Nevis ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('KOR','Republic Of Korea ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('KWT','Kuwait');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('LBN','Libano');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('LBR','Liberia ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('LBY','Libyan Arab Jamahiriya');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('LCA','Saint Lucia ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('LKA','Sri Lanka ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('LTU','Lithuania ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('LUX','Luxemburgo');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('LVA','Latvia');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MAC','Macao ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MAF','San Martin (Parte Holandesa)');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MAR','Morocco ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MCO','Monaco');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MDA','Moldavia');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MDG','Madagascar');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MDV','Maldives');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MEX','Mexico');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MHL','Marshall Islands');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MLI','Ner ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MLT','Malta ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MMR','Myanmar ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MNE','Montenegro');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MNP','Northern Mariana Islands');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MOZ','Mozambique');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MRT','Mauritania');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MSR','Monserrat ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MTQ','Martinique');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MUS','Mauritius ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MYS','Malaysia');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('MYT','Mayotte ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('NAM','Namibia ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('NCL','New Caledonia ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('NGA','Nigeria ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('NIC','Nicaragua ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('NLD','Netherlands ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('NOR','Norway');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('NPL','Nepal ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('NRU','Nauru ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('NZL','New Zealand ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('OMN','Oman');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('PAK','Pakistan');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('PAN','Panama');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('PER','Peru');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('PHL','Philippines ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('PLW','Republica De Palaos ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('PNG','Papua New Guinea');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('POL','Poland');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('PRI','Puerto Rico ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('PRK','Dem PeopleS Rep Of Korea ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('PRT','Portugal');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('PRY','Paraguay');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('PYF','French Polynesia');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('QAT','Qatar ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('REU','Reunion ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('ROU','Bulgaria');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('RUS','Russian Federation');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('SAU','Saudi Arabia');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('SGP','Singapore ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('SHN','Saint Helena');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('SLB','Solomon Islands ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('SLE','Sierra Leone');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('SLV','El Salvador ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('SPM','San Pedro Y Miguelon');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('STP','Sao Tome And Principe ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('SUR','Suriname');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('SVK','Slovaquia ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('SVN','Slovenia');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('SWE','Sweden');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('SYC','Seychelles');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('SYR','Jordan');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('TCA','Turks And Caicos Islands');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('TGO','Togo');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('THA','Thailand');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('TLS','Timor-Leste ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('TON','Tonga ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('TTO','Trinidad And Tobago ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('TUN','Tunisia ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('TUR','Turkey');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('TUV','Tuvalu');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('TWN','China ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('TZA','Cod ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('UKR','Ukraine ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('URY','Uruguay ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('USA','United States Of America');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('VCT','Saint Vincent And The Grenadines');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('VEN','Venezuela ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('VGB','British Virgin Islands');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('VIR','United States Virgin Island ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('VNM','Viet Nam');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('VUT','Vanuatu ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('WLF','Wallis YFutura, Islas ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('WSM','Samoa ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('YEM','Yemen ');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('ZAF','South Africa');
INSERT INTO simar.paises (abreviatura_pais, nombre) VALUES('SEN','Senegal');
